CREATE EXTERNAL FILE FORMAT VENDAS_CSV_FORMAT
WITH
(
    FORMAT_TYPE = DELIMITEDTEXT,
    FORMAT_OPTIONS
    (
        FIELD_TERMINATOR = ',', 
        STRING_DELIMITER = '"',
        FIRST_ROW = 2,
        PARSER_VERSION = '2.0',
        USE_TYPE_DEFAULT = False
    )
);